format_code_in_doc_comments = true
imports_layout ="HorizontalVertical"
imports_granularity ="Crate"
group_imports ="StdExternalCrate"
match_block_trailing_comma = true
edition = "2024"
style_edition ="2024"
